image:
  repository: neo9sas/scale-to-zero-controller
  pullPolicy: Always
  tag: latest

deployment:
  annotations:
    downscaler/exclude: "true"

pod:
  extraEnvMap:
    LOGGING_LEVEL_IO_NEO9_SCALER: INFO

# remove proxy jump to directly have to the pod at the origin of the request
#       source -> tcpHandler
# and not
#       source -> envoy -> tcphandler
podAnnotations:
  sidecar.istio.io/inject: "false"

serviceAccount:
  create: true
  name: "scale-to-zero-controller-sa"

healthCheck:
  path: "/actuator/health"

service:
  port: 15099
  labels:
    scaling.neo9.io/is-scaler: "true"

ingress:
  annotations:
    kubernetes.io/ingress.class: "nginx"
    external-dns.alpha.kubernetes.io/ttl: "5"
    nginx.ingress.kubernetes.io/whitelist-source-range: 52.47.163.232/32,127.0.0.0/8

clusterrole:
  enabled: true
  autoBindClusteRole: true
  rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log", "services"]
    verbs: ["watch", "get", "list"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["get", "create"]
  - apiGroups: ["discovery.k8s.io"]
    resources: ["endpointslices"]
    verbs: ["watch", "get", "list", "update", "patch"]
  - apiGroups: ["apps", "extensions"]
    resources: ["deployments", "statefulsets"]
    verbs: ["watch", "get", "list", "update", "patch"]

# only required if you want/need to bind privileged ports (80 for example).
# you may not want that, it means that the container run as root !
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    add:
      - NET_BIND_SERVICE
    drop:
      - ALL
  runAsUser: 0
