image:
  repository: neo9sas/scale-to-zero-controller
  pullPolicy: Always
  tag: latest

pod:
  extraEnvMap:
    LOGGING_LEVEL_IO_NEO9_SCALER: INFO

# remove proxy jump to directly have to the pod at the origin of the request
#       source -> tcpHandler
# and not
#       source -> envoy -> tcphandler
podAnnotations:
  sidecar.istio.io/inject: "false"

serviceAccount:
  create: true
  name: "scale-to-zero-controller-sa"

healthCheck:
  path: "/actuator/health"

service:
  port: 15099
  labels:
    scaling.neo9.io/is-scaler: "true"

clusterrole:
  enabled: true
  autoBindClusteRole: true
  rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log", "services"]
    verbs: ["watch", "get", "list"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["get", "create"]
  - apiGroups: ["discovery.k8s.io"]
    resources: ["endpointslices"]
    verbs: ["watch", "get", "list", "update", "patch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets"]
    verbs: ["watch", "get", "list", "update", "patch"]
