apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoserver-deployment
  namespace: dev-xmichel
  labels:
    app.kubernetes.io/name: "echoserver"
    app.kubernetes.io/version: "1.4"
    app.kubernetes.io/instance: "echoserver"
    scaling.neo9.io/is-scalable: "true"
spec:
  selector:
    matchLabels:
      app: echoserver-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: echoserver-deployment
    spec:
      containers:
        - name: echoserver
          image: k8s.gcr.io/echoserver:1.4
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    scaling.neo9.io/is-scalable: "true"
    app.kubernetes.io/name: "echoserver"
    app.kubernetes.io/version: "1.4"
    app.kubernetes.io/instance: "echoserver"
    ingress.neo9.io/expose: "true"
  annotations:
    ingress.neo9.io/expose-labels: |-
      ingress.neo9.io/access-operator-enabled: "true"
    ingress.neo9.io/expose-annotations: |-
      kubernetes.io/ingress.class: nginx-istio
      external-dns.alpha.kubernetes.io/ttl: "5"
      ingress.neo9.io/allowed-visitors: neo9
  name: echoserver-deployment
  namespace: dev-xmichel
spec:
  selector:
    app: echoserver-deployment
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
