server:
  port: 15099

spring:
  main:
    banner-mode: "off"

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    io.neo9.scaler: DEBUG
    #io.javaoperatorsdk.operator: WARN

javaoperatorsdk:
  controllers:
    visitorgroupcontroller:
      retry:
        maxAttempts: 3

scaler:
  applicationIdentifierLabels:
    - app.kubernetes.io/name
    - app.kubernetes.io/instance
  # used for splash screen
  publicUrl: http://127.0.0.1:15099
  envNameMatchers:
    - regex: "^.*\\.(.*)\\.neokube\\.neo9\\.pro$"
      prefix: ""
      suffix: ""
