apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoserver-deployment
  namespace: default
  labels:
    app.kubernetes.io/name: "echoserver-deployment"
    app.kubernetes.io/instance: "echoserver-deployment"
    scaling.neo9.io/is-scalable: "true"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: "echoserver-deployment"
      app.kubernetes.io/instance: "echoserver-deployment"
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "echoserver-deployment"
        app.kubernetes.io/instance: "echoserver-deployment"
    spec:
      containers:
        - name: echoserver
          image: k8s.gcr.io/echoserver:1.4
          ports:
            - containerPort: 8080
          readinessProbe:
            successThreshold: 1
            failureThreshold: 3
            periodSeconds: 10
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
---
apiVersion: v1
kind: Service
metadata:
  name: echoserver-deployment
  namespace: default
  labels:
    app.kubernetes.io/name: "echoserver-deployment"
    app.kubernetes.io/instance: "echoserver-deployment"
    scaling.neo9.io/is-scalable: "true"
spec:
  selector:
    app.kubernetes.io/name: "echoserver-deployment"
    app.kubernetes.io/instance: "echoserver-deployment"
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/service-upstream: "true"
    nginx.ingress.kubernetes.io/whitelist-source-range: 52.47.163.232/32,127.0.0.0/8
  name: echoserver-deployment
spec:
  rules:
  - host: echoserver-deployment.dev-xmichel.neokube.neo9.pro
    http:
      paths:
      - backend:
          service:
            name: echoserver-deployment
            port:
              number: 8080
        path: /
        pathType: Prefix
