apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: app-with-splash-screen
  namespace: default
  labels:
    app.kubernetes.io/name: "app-with-splash-screen"
    app.kubernetes.io/instance: "app-with-splash-screen"
    scaling.neo9.io/is-scalable: "true"
  annotations:
    scaling.neo9.io/show-splash-screen: "true"
spec:
  serviceName: app-with-splash-screen
  selector:
    matchLabels:
      app.kubernetes.io/name: "app-with-splash-screen"
      app.kubernetes.io/instance: "app-with-splash-screen"
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "app-with-splash-screen"
        app.kubernetes.io/instance: "app-with-splash-screen"
    spec:
      containers:
        - name: echoserver
          image: k8s.gcr.io/echoserver:1.4
          ports:
            - containerPort: 8080
          readinessProbe:
            successThreshold: 1 # increase to start slower
            failureThreshold: 3
            periodSeconds: 10
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
---
apiVersion: v1
kind: Service
metadata:
  name: app-with-splash-screen
  namespace: default
  labels:
    app.kubernetes.io/name: "app-with-splash-screen"
    app.kubernetes.io/instance: "app-with-splash-screen"
    scaling.neo9.io/is-scalable: "true"
spec:
  selector:
    app.kubernetes.io/name: "app-with-splash-screen"
    app.kubernetes.io/instance: "app-with-splash-screen"
  clusterIP: None
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: app-with-splash-screen-http
  namespace: default
  labels:
    app.kubernetes.io/name: "app-with-splash-screen"
    app.kubernetes.io/instance: "app-with-splash-screen"
    scaling.neo9.io/is-scalable: "true"
spec:
  selector:
    app.kubernetes.io/name: "app-with-splash-screen"
    app.kubernetes.io/instance: "app-with-splash-screen"
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/service-upstream: "true"
    nginx.ingress.kubernetes.io/whitelist-source-range: 52.47.163.232/32,127.0.0.0/8
  name: app-with-splash-screen
spec:
  rules:
  - host: app-with-splash-screen.default.neokube.neo9.pro
    http:
      paths:
      - backend:
          service:
            name: app-with-splash-screen-http
            port:
              number: 8080
        path: /
        pathType: Prefix
