name: CI on main branch

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Compile
      run: ./gradlew build -x test
    - name: Run tests
      run: ./gradlew test
    - name: Build container image
      run: ./gradlew bootBuildImage
    - name: Upload image
      uses: ishworkh/docker-image-artifact-upload@v1
      with:
        image: "docker.io/neo9sas/scale-to-zero-controller:latest"

  integration-tests:
    needs: [build]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        #k8s_version: [v1.19.12-k3s1, v1.20.8-k3s1, v1.21.2-k3s1, v1.22.1-rc1-k3s1]
        k8s_version: [v1.21.2-k3s1]
    steps:
    - uses: actions/checkout@v2
    - name: Download test image
      uses: ishworkh/docker-image-artifact-download@v1
      with:
        image: "docker.io/neo9sas/scale-to-zero-controller:latest"
    - uses: debianmaster/actions-k3s@master
      id: k3s
      with:
        version: ${{ matrix.k8s_version }}
    - name: test on k3s
      run: |
        docker ps
        cd scripts
        make CLUSTER_NAME=k3s-${{ matrix.k8s_version }} import-image-in-k3s
        make CLUSTER_NAME=k3s-${{ matrix.k8s_version }} start-controller
        ./quick-integration-test.sh || testsFailed=1
        cd -
        exit ${testsFailed}

  #publish:
  #  needs: [build]
  #  runs-on: ubuntu-latest
  #  steps:
  #  - name: Download image
  #    uses: ishworkh/docker-image-artifact-download@v1
  #    with:
  #      image: "docker.io/neo9sas/ingress-access-operator:latest"
  #  - name: Log in to Docker Hub
  #    uses: docker/login-action@v1
  #    with:
  #      username: ${{ secrets.DOCKER_USERNAME }}
  #      password: ${{ secrets.DOCKER_PASSWORD }}
  #  - name: Tag and push image
  #    id: tag_push_docker_image
  #    run: |
  #      docker tag docker.io/neo9sas/ingress-access-operator:latest ${{ secrets.DOCKER_HUB_IMAGE }}:latest
  #      docker push ${{ secrets.DOCKER_HUB_IMAGE }}:latest
#
